[[pages]]
path = "trip_planner/pages/login.py"
name = "Login"
icon = ":lock:"

[[pages]]
path = "trip_planner/app.py"
name = "Home"
icon = ":house:"

[[pages]]
path = "trip_planner/pages/planner.py"
name = "Trip Planner"
icon = ":airplane:"

[[pages]]
path = "trip_planner/pages/settings.py"
name = "Settings"
icon = ":gear:"

[[pages]]
path = "trip_planner/pages/trips.py"
name = "Trips"
icon = ":calendar:"

[[pages]]
path = "trip_planner/pages/new_trip.py"
name = "Create Trip"
icon = ":heavy_plus_sign:"
